[project]
name = "l2cs"
version = "0.0.3"
description = "The official pytorch-cuda implementation of L2CS-Net for gaze estimation and tracking"
authors = [{ name = "Ahmed Abderlrahman" }, { name = "Thorsten Hempel" }]
requires-python = ">=3.12,<3.15"
readme = "README.md"
keywords = [
    "gaze",
    "estimation",
    "eye-tracking",
    "deep-learning",
    "pytorch-cuda",
]
classifiers = ["Programming Language :: Python :: 3"]
dependencies = [
    "matplotlib>=3.3.4",
    "numpy>=2,<2.3.0",
    "opencv-python>=4.5.5",
    "pandas>=1.1.5",
    "Pillow>=8.4.0",
    "scipy>=1.5.4",
    "batch-face>=1.5.4",
]

[project.urls]
homepath = "https://github.com/Ahmednull/L2CS-Net"
repository = "https://github.com/Ahmednull/L2CS-Net"

[dependency-groups]
nvidia = ["torch>=2.9,<3", "torchvision>=0.24,<0.25"]
dev = [
    "pre-commit>=4.4.0,<5",
    "flake8>=7.3.0,<8",
    "isort>=7.0.0,<8",
    "black>=25.9.0,<26",
]

amd = ["torch>=2.9,<3 ", "torchvision>=0.24,<0.25"]

[tool.uv]
default-groups = ["nvidia", "dev"]
conflicts = [
    [
        { group = "nvidia", excludes = [
            "amd",
        ] },
        { group = "amd", excludes = [
            "nvidia",
        ] },
    ],
]
[[tool.uv.index]]
name = "PyPI"
url = "https://pypi.org/simple/"
default = true

[[tool.uv.index]]
name = "pytorch-rocm"
url = "https://download.pytorch.org/whl/rocm6.4"

[[tool.uv.index]]
name = "pytorch-cuda"
url = "https://download.pytorch.org/whl/cu130/"

# [tool.uv.sources]
# torch = { index = "pytorch-cuda" }
# torchvision = { index = "pytorch-cuda" }

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]

[tool.black]
line-length = 100

[tool.isort]
profile = "black"
extend_skip = ["build", "dist", ".venv", ".tox", ".gitignore"]
no_sections = 'true'
